[package]
name = "gt6n"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lotus-script = { path = "../../script-rs/lotus-script" }
lotus-extra = { path = "../../lotus-extra" }
